coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: auto
        threshold: 5%
        if_not_found: success
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
