codecov:
  require_ci_to_pass: true
  max_report_age: 2 # days

coverage:
  precision: 2
  round: down
  range: 70..100

  status:
    project:
      default:
        target: 85% # match your local threshold
        threshold: 2% # allow tiny fluctuation
    patch:
      default:
        target: 85%
        threshold: 2%

ignore:
  - "tests/**"
  - "nextlevelapex/tasks/**"
  - "nextlevelapex/main.py"
  - "nextlevelapex/core/logger.py"
